# Generated by Django 6.1.2 on 2026-10-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('propiedades', '0004_lote'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora'), name='cita_fecha_hora_unica'),
        ),
    ]
