# Generated by Django 6.1.2 on 2026-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('operacion', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ubicacion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Puebla', max_length=100)),
                ('recamaras', models.PositiveIntegerField(default=0)),
                ('banos', models.PositiveIntegerField(default=0)),
                ('estacionamientos', models.PositiveIntegerField(default=0)),
                ('metros_terreno', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metros_construccion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen_principal', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
