# Generated by Django 6.1.2 on 2026-10-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
    ]
