# Generated by Django 6.1.2 on 2026-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_alter_propiedad_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='fondo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='frente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='servicios',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
