# Generated by Django 6.1.2 on 2026-10-06 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_fondo_propiedad_frente_propiedad_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fondo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, default='', max_length=200)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('apartado', 'Apartado'), ('vendido', 'Vendido')], default='disponible', max_length=20)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='propiedades.propiedad')),
            ],
        ),
    ]
